services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: StockAnalysisTool
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    gunicorn app:app -w 2 --threads 2 -b 0.0.0.0:80
   
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
